- build.gradle
- src/main/java/com/reckue/athena/AthenaApplication.java
- src/main/java/com/reckue/athena/configs/SwaggerConfig.java
- Add AthenaApplication
- Add SwaggerConfig
> Create main class and add dependencies

- src/main/java/com/reckue/note/configs/DozerConfig.java
- src/main/java/com/reckue/note/controllers/NoteController.java
- src/main/java/com/reckue/note/models/entities/Note.java
- src/main/java/com/reckue/note/models/forms/NoteForm.java
- src/main/java/com/reckue/note/models/transfers/NoteTransfer.java
- src/main/java/com/reckue/note/repositories/NoteRepository.java
- src/main/java/com/reckue/note/services/NoteService.java
- src/main/java/com/reckue/note/services/impl/NoteServiceMongo.java
- Create service and repository for Notes
- Add CRUD mapping into NoteController
> Add CRUD operations

- src/main/java/com/reckue/note/exceptions/NoteNotFoundException.java
- src/main/java/com/reckue/note/services/NoteServiceMongo.java
Added custom exception and threw note not found exception.
> Add exceptions

- README.md
Closes #17 
This task has been done successfully
> Added the travis ci build status button to README.md.

- src/main/java/com/reckue/note/handlers/CustomErrorHandler.java
- src/main/java/com/reckue/note/handlers/CustomExceptionHandler.java
- src/main/java/com/reckue/note/models/transfers/ErrorTransfer.java
> Add custom handlers and error template class

- src/main/java/com/reckue/post/models/CodeNode.java
- src/main/java/com/reckue/post/models/LangType.java
> Add enum LangType and class CodeNode

- src/main/java/com/reckue/post/models/StatusType.java
> Add enum StatusType

- src/main/java/com/reckue/post/models/Tag.java
> Add class Tag

- src/main/java/com/reckue/post/models/ImageNode.java
> Add class ImageNode

- src/main/java/com/reckue/post/repositories/TextNodeRepository.java
> Add TextNodeRepository

- src/main/java/com/reckue/post/repositories/ImageNodeRepository.java
> Add ImageNodeRepository

- src/main/java/com/reckue/post/repositories/VideoNodeRepository.java
> Add video node repository

- src/main/java/com/reckue/post/models/Node.java
> Add class Node

- src/main/java/com/reckue/post/repositories/CodeNodeRepository.java
> Add code node repository

- src/main/java/com/reckue/post/models/Post.java
> Add class post

- src/main/java/com/reckue/post/repositories/NodeRepository.java
> Add class node repository

- src/main/java/com/reckue/post/models/repositories/VideoNodeRepository.java
> Delete extra repositories package

- src/main/java/com/reckue/post/repositories/ListNodeRepository.java
> Add list node repository

- .gitignore
- src/main/java/com/reckue/post/repositories/PostRepository.java
> Add post repository and changes in .gitignore

- build.gradle
> Add new library for mapping objects

- src/main/java/com/reckue/post/transfers/TextNodeRequest.java
- src/main/java/com/reckue/post/transfers/TextNodeResponse.java
> Add classes request and response for text node

- src/main/java/com/reckue/post/transfers/CodeNodeRequest.java
- src/main/java/com/reckue/post/transfers/CodeNodeResponse.java
> Add classes request and response for model code node

- src/main/java/com/reckue/post/transfers/ImageNodeRequest.java
- src/main/java/com/reckue/post/transfers/ImageNodeResponse.java
> Add transfer for image node model

- src/main/java/com/reckue/post/transfers/ListNodeRequest.java
- src/main/java/com/reckue/post/transfers/ListNodeResponse.java
> Add transfer for list node model

- src/main/java/com/reckue/post/transfers/VideoNodeRequest.java
- src/main/java/com/reckue/post/transfers/VideoNodeResponse.java
> Add classes request and response video node

- src/main/java/com/reckue/post/transfers/TagNodeRequest.java
- src/main/java/com/reckue/post/transfers/TagNodeResponse.java
> Add classes request and response tag node

- src/main/java/com/reckue/post/transfers/NodeRequest.java
- src/main/java/com/reckue/post/transfers/NodeResponse.java
> Add transfer for node model

- src/main/java/com/reckue/post/transfers/PostRequest.java
- src/main/java/com/reckue/post/transfers/PostResponse.java
> Add classes request and response for model post

- src/main/java/com/reckue/post/exceptions/ModelNotFoundException.java
> Revert "Revert "Add model not found exception""

- src/main/java/com/reckue/post/exceptions/ModelAlreadyExistsException.java
> Add model already exists exception

- src/main/java/com/reckue/post/controllers/NodeController.java
- src/main/java/com/reckue/post/controllers/PostController.java
- src/main/java/com/reckue/post/controllers/TagController.java
> Add classes to controllers package 

- src/main/java/com/reckue/post/services/NodeService.java
- src/main/java/com/reckue/post/services/realizations/NodeServiceRealization.java
> Add node service and node service realization

- src/main/java/com/reckue/post/models/Node.java
- src/main/java/com/reckue/post/services/NodeService.java
- src/main/java/com/reckue/post/services/realizations/NodeServiceRealization.java
> Fix find all method in node service realization

- src/main/java/com/reckue/post/exceptions/ModelAlreadyExistsException.java
- src/main/java/com/reckue/post/exceptions/ModelNotFoundException.java
- src/main/java/com/reckue/post/models/Node.java
- src/main/java/com/reckue/post/models/Post.java
- src/main/java/com/reckue/post/services/NodeService.java
- src/main/java/com/reckue/post/services/PostService.java
- src/main/java/com/reckue/post/services/realizations/NodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/PostServiceRealization.java
> Add post service, realization and changes in note service realization

- src/main/java/com/reckue/post/services/VideoNodeService.java
- src/main/java/com/reckue/post/services/realizations/VideoNodeServiceRealization.java
> Add video node service and realization

- src/main/java/com/reckue/post/models/CodeNode.java
- src/main/java/com/reckue/post/services/CodeNodeService.java
- src/main/java/com/reckue/post/services/NodeService.java
- src/main/java/com/reckue/post/services/PostService.java
- src/main/java/com/reckue/post/services/realizations/CodeNodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/NodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/PostServiceRealization.java
> Add code node service realization and changes

- src/main/java/com/reckue/post/config/SwaggerConfig.java
> Add configuration of swagger ui

- src/main/java/com/reckue/post/exceptions/ModelNotFoundException.java
- src/main/java/com/reckue/post/services/ImageNodeService.java
- src/main/java/com/reckue/post/services/TextNodeService.java
- src/main/java/com/reckue/post/services/realizations/ImageNodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/TextNodeServiceRealization.java
> Add image node service

- src/main/java/com/reckue/post/services/realizations/CodeNodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/ImageNodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/NodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/PostServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/TagServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/TextNodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/VideoNodeServiceRealization.java
> Add changes in methods in all service realizations

- build.gradle
- src/main/java/com/reckue/post/config/SwaggerConfig.java
> Add redirect to swagger ui

- .gitignore
- build.gradle
- config/checkstyle/report.xsl
- src/main/java/com/reckue/post/configs/SwaggerConfiguration.java
> Fix dependencies list, git ignore, swagger, checkstyle

- src/main/java/com/reckue/post/utils/Generator.java
> Add identifier generator

- build.gradle
- src/main/java/com/reckue/post/controllers/NodeController.java
- src/main/java/com/reckue/post/converters/NodeConverter.java
- src/main/java/com/reckue/post/services/realizations/NodeServiceRealization.java
- src/main/java/com/reckue/post/transfers/NodeRequest.java
- src/main/java/com/reckue/post/transfers/NodeResponse.java
> Add node controller

- src/main/java/com/reckue/post/controllers/PostController.java
- src/main/java/com/reckue/post/converters/PostConverter.java
- src/main/java/com/reckue/post/services/realizations/PostServiceRealization.java
- src/main/java/com/reckue/post/transfers/PostRequest.java
- src/main/java/com/reckue/post/transfers/PostResponse.java
> Add post controller

- src/main/java/com/reckue/post/controllers/TagController.java
- src/main/java/com/reckue/post/converters/TagConverter.java
- src/main/java/com/reckue/post/models/Post.java
- src/main/java/com/reckue/post/models/Tag.java
- src/main/java/com/reckue/post/repositories/PostRepository.java
- src/main/java/com/reckue/post/services/realizations/TagServiceRealization.java
- src/main/java/com/reckue/post/transfers/TagRequest.java
- src/main/java/com/reckue/post/transfers/TagResponse.java
> Add tag controller

- src/main/java/com/reckue/post/utils/Generator.java
> Add javadoc for generator class

- src/main/java/com/reckue/post/controllers/NodeController.java
- src/main/java/com/reckue/post/transfers/CodeNodeRequest.java
- src/main/java/com/reckue/post/transfers/ImageNodeRequest.java
- src/main/java/com/reckue/post/transfers/NodeRequest.java
- src/main/java/com/reckue/post/transfers/PostRequest.java
- src/main/java/com/reckue/post/transfers/TagRequest.java
- src/main/java/com/reckue/post/transfers/TextNodeRequest.java
- src/main/java/com/reckue/post/transfers/VideoNodeRequest.java
> Add validation for nodes

- src/main/java/com/reckue/post/services/realizations/CodeNodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/ImageNodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/NodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/PostServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/TagServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/TextNodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/VideoNodeServiceRealization.java
> Add better description of exceptions

- build.gradle
- src/main/java/com/reckue/post/controllers/PostController.java
- src/main/resources/application.yml
> Add validation in post controller

- build.gradle
- src/main/java/com/reckue/post/configs/MongobeeConfig.java
> Add migrations

- src/main/java/com/reckue/post/controllers/TagController.java
> Add validation for tag controller

- README.md
> Add stack and build project

- src/main/java/com/reckue/post/services/realizations/CodeNodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/ImageNodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/NodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/PostServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/TagServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/TextNodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/VideoNodeServiceRealization.java
> Change generation id logic

- src/main/java/com/reckue/post/utils/converters/Converter.java
> Converts list for converter class

- src/main/java/com/reckue/post/models/CodeNode.java
- src/main/java/com/reckue/post/models/ImageNode.java
- src/main/java/com/reckue/post/models/LangType.java
- src/main/java/com/reckue/post/models/ListNode.java
- src/main/java/com/reckue/post/models/Node.java
- src/main/java/com/reckue/post/models/NodeType.java
- src/main/java/com/reckue/post/models/Post.java
- src/main/java/com/reckue/post/models/StatusType.java
- src/main/java/com/reckue/post/models/Tag.java
- src/main/java/com/reckue/post/models/TextNode.java
- src/main/java/com/reckue/post/models/VideoNode.java
> Add javadocs in models

- src/main/java/com/reckue/post/services/realizations/NodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/PostServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/TagServiceRealization.java
> Fix limit and offset in services

- build.gradle
- src/main/java/com/reckue/post/configs/MigrationConfiguration.java
- src/main/java/com/reckue/post/repositories/PostRepository.java
- src/main/java/com/reckue/post/services/realizations/NodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/PostServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/TagServiceRealization.java
- src/main/resources/application.yml
> Add configuration for mongobee

- src/main/java/com/reckue/post/configs/DatabaseConfiguration.java
- src/main/resources/application.yml
> Fix mongo configuration and fix profiles

- .github/workflows/config.yml
> Add github workflow config

- src/main/java/com/reckue/post/models/Tag.java
- src/main/java/com/reckue/post/transfers/TagResponse.java
- src/test/java/com/reckue/post/utils/converters/ConverterTest.java
> Add test for convertor class

- src/main/java/com/reckue/post/transfers/TagRequest.java
- src/main/java/com/reckue/post/transfers/TagResponse.java
- src/test/java/com/reckue/post/controllers/NodeControllerIntTest.java
- src/test/java/com/reckue/post/controllers/TagControllerIntTest.java
> Add tag controller integration test

- src/main/java/com/reckue/post/controllers/PostController.java
- src/main/java/com/reckue/post/controllers/apis/NodeApi.java
- src/main/java/com/reckue/post/controllers/apis/PostApi.java
- src/main/java/com/reckue/post/exceptions/ModelAlreadyExistsException.java
- src/main/java/com/reckue/post/exceptions/ModelNotFoundException.java
- src/main/java/com/reckue/post/models/LangType.java
- src/main/java/com/reckue/post/models/NodeType.java
- src/main/java/com/reckue/post/models/StatusType.java
- src/main/java/com/reckue/post/services/realizations/NodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/PostServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/TagServiceRealization.java
- src/test/java/com/reckue/post/controllers/PostControllerIntTest.java
Correct javadoc
optimize imports
add annotation
> Fix several bugs

- src/test/java/com/reckue/post/controllers/NodeControllerIntTest.java
- src/test/java/com/reckue/post/controllers/PostControllerIntTest.java
- src/test/java/com/reckue/post/controllers/TagControllerIntTest.java
- src/test/java/com/reckue/post/services/realizations/NodeServiceRealizationTest.java
- src/test/java/com/reckue/post/services/realizations/PostServiceRealizationTest.java
- src/test/java/com/reckue/post/services/realizations/TagServiceRealizationUnitTest.java
Delete extra empty line
delete annotations
> Fix bugs in test package

- src/main/java/com/reckue/post/models/AudioNode.java
> Add audio node model

- src/main/java/com/reckue/post/models/NodeType.java
- src/main/java/com/reckue/post/transfers/AudioNodeRequest.java
- src/main/java/com/reckue/post/transfers/AudioNodeResponse.java
> Add audio node transfer and type audio in node type enum

- src/main/java/com/reckue/post/controllers/RatingController.java
- src/main/java/com/reckue/post/controllers/apis/RatingApi.java
- src/main/java/com/reckue/post/models/Rating.java
- src/main/java/com/reckue/post/repositories/RatingRepository.java
- src/main/java/com/reckue/post/services/RatingService.java
- src/main/java/com/reckue/post/services/realizations/RatingServiceRealization.java
- src/main/java/com/reckue/post/transfers/RatingRequest.java
- src/main/java/com/reckue/post/transfers/RatingResponse.java
- src/main/java/com/reckue/post/utils/converters/RatingConverter.java
- src/test/java/com/reckue/post/controllers/RatingControllerIntTest.java
- src/test/java/com/reckue/post/services/realizations/RatingServiceRealizationTest.java
add Rating classes
add RatingControllerIntTest
> Add rating classes

- src/main/java/com/reckue/post/configs/SwaggerConfiguration.java
- src/main/java/com/reckue/post/models/Node.java
- src/main/java/com/reckue/post/models/nodes/Parent.java
- src/main/java/com/reckue/post/models/nodes/PollNode.java
- src/main/java/com/reckue/post/repositories/NodeRepository.java
- src/main/java/com/reckue/post/repositories/PollNodeRepository.java
- src/main/java/com/reckue/post/repositories/PostRepository.java
- src/main/java/com/reckue/post/repositories/TagRepository.java
- src/main/java/com/reckue/post/services/realizations/NodeServiceRealization.java
- src/main/java/com/reckue/post/transfers/NodeRequest.java
- src/main/java/com/reckue/post/transfers/NodeResponse.java
- src/main/java/com/reckue/post/transfers/nodes/NodeParentRequest.java
- src/main/java/com/reckue/post/transfers/nodes/NodeParentResponse.java
- src/main/java/com/reckue/post/transfers/nodes/video/VideoNodeResponse.java
- src/main/java/com/reckue/post/utils/Generator.java
- src/main/java/com/reckue/post/utils/converters/Converter.java
- src/main/java/com/reckue/post/utils/converters/PostConverter.java
> Add changes to javadocs and optimize imports

- src/main/java/com/reckue/post/utils/converters/NodeConverter.java
> Add post id to node converter

- src/test/java/com/reckue/post/controllers/NodeControllerIntTest.java
- src/test/java/com/reckue/post/controllers/PostControllerIntTest.java
- src/test/java/com/reckue/post/controllers/TagControllerIntTest.java
> Optimize methods with sort descending

- src/main/java/com/reckue/post/services/realizations/RatingServiceRealization.java
- src/test/java/com/reckue/post/controllers/RatingControllerIntTest.java
- src/test/java/com/reckue/post/services/realizations/RatingServiceRealizationTest.java
> Fix rating problems

- src/main/java/com/reckue/post/controllers/PostController.java
- src/main/java/com/reckue/post/repositories/PostRepository.java
- src/main/java/com/reckue/post/services/PostService.java
- src/main/java/com/reckue/post/services/realizations/PostServiceRealization.java
> Add search by post title

- src/main/java/com/reckue/post/controllers/DataBaseUtilController.java
- src/main/java/com/reckue/post/controllers/apis/DataBaseUtilApi.java
- src/main/java/com/reckue/post/services/NodeService.java
- src/main/java/com/reckue/post/services/PostService.java
- src/main/java/com/reckue/post/services/realizations/NodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/PostServiceRealization.java
Closes #318 
Closes #319 
Closes #320
> Add util class for work with DB

- src/main/java/com/reckue/post/transfers/PostRequest.java
> Add settings to post request

- src/main/java/com/reckue/post/services/realizations/RatingServiceRealization.java
> Add logic changes in the method

- src/main/java/com/reckue/post/services/realizations/RatingServiceRealization.java
#352 
reverted back one line of old code
> Fix rating logic

- src/main/java/com/reckue/post/services/BaseService.java
- src/main/java/com/reckue/post/services/CommentService.java
- src/main/java/com/reckue/post/services/NodeService.java
- src/main/java/com/reckue/post/services/PollNodeService.java
- src/main/java/com/reckue/post/services/PostService.java
- src/main/java/com/reckue/post/services/RatingService.java
- src/main/java/com/reckue/post/services/TagService.java
- src/main/java/com/reckue/post/services/realizations/CommentServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/PollNodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/RatingServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/TagServiceRealization.java
> Add base service

- src/main/java/com/reckue/post/exceptions/models/comment/CommentAlreadyExistsException.java
- src/main/java/com/reckue/post/exceptions/models/comment/CommentNotFoundException.java
- src/main/java/com/reckue/post/exceptions/models/nodes/NodeAlreadyExistsException.java
- src/main/java/com/reckue/post/exceptions/models/nodes/NodeNotFoundException.java
- src/main/java/com/reckue/post/exceptions/models/nodes/pollnode/PollNodeAlreadyExistsException.java
- src/main/java/com/reckue/post/exceptions/models/nodes/pollnode/PollNodeNotFoundException.java
- src/main/java/com/reckue/post/exceptions/models/post/PostAlreadyExistsException.java
- src/main/java/com/reckue/post/exceptions/models/rating/RatingAlreadyExistsException.java
- src/main/java/com/reckue/post/exceptions/models/rating/RatingNotFoundException.java
- src/main/java/com/reckue/post/exceptions/models/tag/TagAlreadyExistsException.java
- src/main/java/com/reckue/post/exceptions/models/tag/TagNotFoundException.java
- src/main/java/com/reckue/post/exceptions/models/user/UserAlreadyExistsException.java
- src/main/java/com/reckue/post/exceptions/models/user/UserNotFoundException.java
@SuppressWarnings("unused") where constructors have never been used.
> Add annotation to exception package 

- src/main/java/com/reckue/post/models/Comment.java
- src/main/java/com/reckue/post/models/Post.java
- src/main/java/com/reckue/post/services/realizations/CommentServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/PostServiceRealization.java
> Fix using the cloneable

- src/main/java/com/reckue/post/controllers/apis/PostApi.java
- src/main/java/com/reckue/post/handlers/CustomExceptionHandler.java
- src/main/java/com/reckue/post/repositories/NodeRepository.java
- src/main/java/com/reckue/post/services/realizations/CommentServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/PostServiceRealization.java
- src/test/java/com/reckue/post/services/realizations/CommentServiceRealizationTest.java
- src/test/java/com/reckue/post/services/realizations/PostServiceRealizationTest.java
> Fix the binding nodes

- src/main/resources/openapi/post.yml
> Open api generation

- src/main/java/com/reckue/post/controllers/ResourceController.java
> Fix resource controller name

- src/main/java/com/reckue/post/controllers/CommentController.java
- src/main/java/com/reckue/post/controllers/NodeController.java
- src/main/java/com/reckue/post/controllers/PostController.java
- src/main/java/com/reckue/post/controllers/RatingController.java
- src/main/java/com/reckue/post/services/AuthService.java
- src/main/java/com/reckue/post/services/SecurityService.java
- src/main/java/com/reckue/post/services/SecurityServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/CommentServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/NodeServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/PostServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/RatingServiceRealization.java
- src/main/java/com/reckue/post/services/realizations/SecurityServiceRealization.java
- src/test/java/com/reckue/post/services/realizations/CommentServiceRealizationTest.java
- src/test/java/com/reckue/post/services/realizations/PostServiceRealizationTest.java
- src/test/java/com/reckue/post/services/realizations/RatingServiceRealizationTest.java
> Add security service and move there the secure part

- build.gradle
- src/test/java/com/reckue/post/sandbox/Sandbox.java
> Add Sandbox class and gradle run script
